// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    BaseAudio: typeof import('./../components/BaseAudio.vue')['default']
    BaseBarChart: typeof import('./../pages/HomePage/components/health/BaseBarChart.vue')['default']
    BaseClock: typeof import('./../components/BaseClock.vue')['default']
    BaseGaugeChart: typeof import('./../pages/HomePage/components/health/BaseGaugeChart.vue')['default']
    BaseKpi: typeof import('./../components/BaseKpi.vue')['default']
    BaseLineChart: typeof import('./../pages/HomePage/components/health/BaseLineChart.vue')['default']
    BasePieChart: typeof import('./../pages/HomePage/components/health/BasePieChart.vue')['default']
    BaseScatterChartOne: typeof import('./../pages/HomePage/components/health/BaseScatterChartOne.vue')['default']
    BaseScatterChartTwo: typeof import('./../pages/HomePage/components/health/BaseScatterChartTwo.vue')['default']
    BaseScatterDiagram: typeof import('./../pages/HomePage/components/health/BaseScatterDiagram.vue')['default']
    BaseSwitchTabs: typeof import('./../components/BaseSwitchTabs.vue')['default']
    BaseTable: typeof import('./../pages/HomePage/components/health/BaseTable.vue')['default']
    BaseWeather: typeof import('./../components/BaseWeather.vue')['default']
    BaseYearSelect: typeof import('./../components/BaseYearSelect.vue')['default']
    HomePage: typeof import('./../pages/HomePage/HomePage.vue')['default']
    HomePageDrawer: typeof import('./../pages/HomePage/components/HomePageDrawer.vue')['default']
    HomePageForHealth: typeof import('./../pages/HomePage/components/HomePageForHealth.vue')['default']
    HomePageForRead: typeof import('./../pages/HomePage/components/HomePageForRead.vue')['default']
    Login: typeof import('./../pages/Login/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
